name: Run tests

on:
  push:
    branches:
      - "**"

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run Unit Tests
        run: |
          uv run pytest -vv -s --cov=work_tracker --cov-config=pyproject.toml --ignore=tests/e2e.py

      - name: Run E2E Tests
        run: |
          uv run pytest -vv -s tests/e2e.py